"""
Generates a one-page PDF incident report for a single investigation record,
SOC-style: summary, IOC details, GeoIP, MITRE mapping, recommended action.
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")


def _verdict_color(verdict):
    return {
        "malicious": colors.HexColor("#e74c3c"),
        "suspicious": colors.HexColor("#f39c12"),
        "clean": colors.HexColor("#2ecc71"),
    }.get(verdict, colors.grey)


def _recommended_action(verdict):
    return {
        "malicious": "Block IOC at firewall/proxy immediately. Isolate affected host. Escalate to Tier 2 for full IR.",
        "suspicious": "Add to watchlist. Monitor for repeated activity. Re-scan in 24 hours.",
        "clean": "No action required. Close investigation.",
    }.get(verdict, "Review manually.")


def generate_pdf_report(record):
    os.makedirs(REPORTS_DIR, exist_ok=True)
    filepath = os.path.join(REPORTS_DIR, f"incident_report_{record['id']}.pdf")

    doc = SimpleDocTemplate(filepath, pagesize=A4,
                             topMargin=20 * mm, bottomMargin=20 * mm,
                             leftMargin=20 * mm, rightMargin=20 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Heading1"], fontSize=18,
                                  textColor=colors.HexColor("#1a1a2e"))
    heading_style = ParagraphStyle("heading", parent=styles["Heading2"], fontSize=12,
                                    textColor=colors.HexColor("#1a1a2e"), spaceBefore=10)
    normal = styles["Normal"]

    elements = []
    elements.append(Paragraph("Threat Hunting Dashboard — Incident Report", title_style))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(f"Generated: {record['timestamp']}", normal))
    elements.append(Spacer(1, 12))

    verdict = record.get("verdict", "unknown")
    verdict_table = Table([["Verdict", verdict.upper()]], colWidths=[100, 380])
    verdict_table.setStyle(TableStyle([
        ("BACKGROUND", (1, 0), (1, 0), _verdict_color(verdict)),
        ("TEXTCOLOR", (1, 0), (1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (1, 0), "CENTER"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(verdict_table)
    elements.append(Spacer(1, 14))

    elements.append(Paragraph("IOC Details", heading_style))
    ioc_data = [
        ["IOC", record.get("ioc")],
        ["Type", record.get("ioc_type")],
        ["Malicious votes", f"{record.get('malicious_votes')} / {record.get('total_votes')}"],
        ["Threat category", record.get("threat_category")],
        ["Source", record.get("source")],
    ]
    t1 = Table(ioc_data, colWidths=[140, 340])
    t1.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("PADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t1)
    elements.append(Spacer(1, 14))

    geo = record.get("geo")
    if geo:
        elements.append(Paragraph("GeoIP — Attacker Location", heading_style))
        geo_data = [
            ["Country", geo.get("country", "-")],
            ["City", geo.get("city", "-")],
            ["ISP", geo.get("isp", "-")],
            ["Coordinates", f"{geo.get('lat', '-')}, {geo.get('lon', '-')}"],
        ]
        t2 = Table(geo_data, colWidths=[140, 340])
        t2.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
            ("PADDING", (0, 0), (-1, -1), 5),
        ]))
        elements.append(t2)
        elements.append(Spacer(1, 14))

    mitre = record.get("mitre", {})
    elements.append(Paragraph("MITRE ATT&CK Mapping", heading_style))
    mitre_data = [
        ["Tactic", mitre.get("tactic", "-")],
        ["Technique ID", mitre.get("technique_id", "-")],
        ["Technique", mitre.get("technique_name", "-")],
    ]
    t3 = Table(mitre_data, colWidths=[140, 340])
    t3.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("PADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t3)
    elements.append(Spacer(1, 14))

    elements.append(Paragraph("Recommended Action", heading_style))
    elements.append(Paragraph(_recommended_action(verdict), normal))
    elements.append(Spacer(1, 20))

    elements.append(Paragraph(
        "Generated by Threat Hunting Dashboard | github.com/vasanth-void-0x/Threat-Hunting-Dashboard",
        ParagraphStyle("footer", parent=normal, fontSize=8, textColor=colors.grey)
    ))

    doc.build(elements)
    return filepath
